### ISSUE TITLE
It is not a good practice to use htmlFor

### ISSUE THREAD

**Issue by ghost** [AlexsanderKevin/origamid-react#4]
https://github.com/AlexsanderKevin/origamid-react/blob/a90833df89bfa37f7861d203be9f928ca56af9f6/appreact/src/App.js#L16

**Comment by AlexsanderKevin** [comment]
Thanks to telling me.
Could you explain to me why is that a bad practice?

**Comment by ghost** [comment]
por que gente do bem mesmo nem front faz, to tirando uma com a sua cara só relaxa
